In [1]:
import scipy as sp
import numpy as np

In [2]:
text = "I am learning Natural Language Processing. Natural Language Processing is interesting."

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

Convert a collection of text documents to a matrix of token counts.               
CountVectorizer doesn't have normalization, it just counts the number of times a word appears in the text. It does not take into account the length of the document or the frequency of the word in the corpus. This can lead to issues when comparing documents of different lengths or when comparing words that appear frequently in the corpus.

In [10]:
vector = CountVectorizer()
vector.fit([text])
matrix = vector.transform([text]).toarray() # convert the text into a matrix of token counts
print(vector.vocabulary_)   # get the vocabulary of the text
print(matrix)   # get the matrix of token counts

{'am': 0, 'learning': 4, 'natural': 5, 'language': 3, 'processing': 6, 'is': 2, 'interesting': 1}
[[1 1 1 2 1 2 2]]


In [11]:
str = "i love natural language processing"
tokens =str.split()
print(tokens)

['i', 'love', 'natural', 'language', 'processing']


# Punctuation
Punctuation may be important for some downstream tasks like sentiment analysis.
So tokenizing punctuation may be important for some tasks.
CountVectorizer by default removes punctuation, but we can change this behavior by setting the `token_pattern` parameter to include punctuation. For example, we can set `token_pattern=r'\b\w+\b|[^\w\s]'` to include both words and punctuation as tokens. This will allow us to capture the punctuation in the text, which may be important for certain tasks.

In [15]:
txt = "hi, how are you doing?"
word_vectorizer = CountVectorizer(analyzer='word', token_pattern=r'\b\w+\b|[^\w\s]')
word_vectorizer.fit([txt])
word_matrix = word_vectorizer.transform([txt]).toarray()
print(word_vectorizer.vocabulary_)
print(word_matrix)

{'hi': 4, ',': 0, 'how': 5, 'are': 2, 'you': 6, 'doing': 3, '?': 1}
[[1 1 1 1 1 1 1]]


In [16]:
# Stopwords in count vectorizer
token = CountVectorizer(stop_words='english')
token.fit([text])
token_matrix = token.transform([text]).toarray()
print(token.vocabulary_)
print(token_matrix) 

{'learning': 2, 'natural': 3, 'language': 1, 'processing': 4, 'interesting': 0}
[[1 2 1 2 2]]
